### PR TITLE
[Breaking Change] Change manifest to object from array

### PR DESCRIPTION
**Pull request by darthmaim**
The manifest is just an array of addons right now (`Addon[]`), this changes the the manifest to be an object (`{ addons: Addon[] }`) so we can add additional data later.

This is a breaking change (cc @TheMrMilchmann)

### CODE REVIEW

**Comment by TheMrMilchmann** [comment]
While we're at it, can we also add versioning to the manifest? I propose wrapping the current format in:

```json
{
  "version": 1,
  "data": { ... }
}
```

This way, we could increment the version number for incompatible changes requiring manager adjustments. The manager could then prompt that an update is necessary.

Effectively, we can prevent crashes or odd behavior due to format changes this way.

**Comment by darthmaim** [comment]
I thought about this too, but what is the addon manager going to do if it discovers a version 2 manifest, but only supports version 1?
I think it would be better, if we were to ever change the manifest version, to release the manifest as `manifest.v2.json` or so, and still keep the v1 up (either as static, or by writing some code that generates a v1 manifest from v2). That way the addon manager can load whatever manifest it supports.

**Comment by TheMrMilchmann** [comment]
> I thought about this too, but what is the addon manager going to do if it discovers a version 2 manifest, but only supports version 1?

We'll have to make sure that we only generate new manifest versions after releasing a manager version with support for it. Then, if the manager discovers an unsupported manifest, we just prompt that an update is necessary. I don't expect us to change the manifest version too often, so this should be perfectly fine - especially considering that manager changes will be necessary anyway.

> I think it would be better, if we were to ever change the manifest version, to release the manifest as manifest.v2.json or so, and still keep the v1 up (either as static, or by writing some code that generates a v1 manifest from v2). That way the addon manager can load whatever manifest it supports.

I can immediately think of two reasons against this:

1. This can (and is likely to) significantly complicate generation. For example, if we implement changes to how add-ons are downloaded (like new strategies for different release channels), we could end up with some add-ons that are only supported in a later version of the manifest.
2. We effectively end up with multiple supported versions this way. This adds a lot of overhead and user-facing complexity (as users would be able to see different add-ons based on the manager version). However, we don't have to and should not support old versions of the manager. I don't want to run into scenarios, where we have to ask users to update the manager.

**Comment by darthmaim** [comment]
Hmm, you have some good points 👍 

I can just add a version. Do you need the `data` wrapper to deserialize it easier or would `{ version: 1, addons: [] }` instead of `{ version: 1, data: { addons: [] }}` also work for you?

**Comment by TheMrMilchmann** [comment]
> Hmm, you have some good points 👍
> 
> I can just add a version. Do you need the `data` wrapper to deserialize it easier or would `{ version: 1, addons: [] }` instead of `{ version: 1, data: { addons: [] }}` also work for you?

Deserialization with the stuff wrapped in `data` is significantly cleaner and easier. Also, since this file is not meant to be read by humans, I don't think the additional nesting matters.

> Then we would also have to change the toml schema, or map when generating the manifest. Mapping just in the manager is fine I think...

I don't have a strong opinion here. The manager will use camelCase to follow Kotlin conventions, but we can keep the manifest as-is.

**Comment by darthmaim** [comment]
I've added `version` and `data` 👍 

snake_case is the most common casing for toml files, but json (and js) is usually camelCase. So we probably should already map when deserializing the toml files 🤔

**Comment by knoxfighter** [comment]
What happens with the existing manifest in the old format? Does that cause this to fail or would that just generate a new one and override the old one?

**Comment by darthmaim** [comment]
Good you mentioned that, I forgot to update reading the existing manifest. I've now added a manifest schema, so we make sure we can read what we are writing. We probably need a test that verifies that merging works to prevent similar issues in the future.

This should just fail one time to read the existing manifest, and generate a new one.

**Comment by darthmaim** [comment]
I've added a method that can read old array manifests (we can remove that in the future).

I've also added tests that make sure we can read and merge both array manifests and the new object manifests.

**Pull request merged**
